[versions]
aws-cdk = "2.221.1"
aws-cdk-alpha = "2.221.1-alpha.0"
github-spotbugs = "4.9.8"
jackson = "2.19.4"

[libraries]
apache-commons-text = { module = "org.apache.commons:commons-text", version = "1.14.0" }
apache-httpcomponents-httpcore = { module = "org.apache.httpcomponents:httpcore", version = "4.4.16" }
apache-pdfbox = { module = "org.apache.pdfbox:pdfbox", version = "2.0.35" }
aws-cdk-lib = { module = "software.amazon.awscdk:aws-cdk-lib", version.ref = "aws-cdk" }
aws-cdk-amplify-alpha = { module = "software.amazon.awscdk:amplify-alpha", version.ref = "aws-cdk-alpha" }
aws-lambda-java-core = { module = "com.amazonaws:aws-lambda-java-core", version = "1.4.0" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version = "3.16.1" }
aws-lambda-java-events-transformer = { module = "com.amazonaws:aws-lambda-java-events-sdk-transformer", version = "3.1.1" }
aws-lambda-snapstart-java-rules = { module = "software.amazon.lambda.snapstart:aws-lambda-snapstart-java-rules", version = "0.2.1" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version = "2.37.3" }
commons-codec = { module = "commons-codec:commons-codec", version = "1.19.0" }
commons-validator = { module = "commons-validator:commons-validator", version = "1.10.0" }
constructs = { module = "software.constructs:constructs", version = "10.4.2" }
github-spotbugs = { module = "com.github.spotbugs:spotbugs", version.ref = "github-spotbugs" }
github-spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "github-spotbugs" }
googlecode-lanterna = { module = "com.googlecode.lanterna:lanterna", version = "3.1.3" }
googlecode-libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version = "9.0.17" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
jug = { module = "com.fasterxml.uuid:java-uuid-generator", version = "5.1.1" }
leego-banana = { module = "io.leego:banana", version = "2.1.0" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }
milton-api = { module = "io.milton:milton-api", version = "4.0.5.2500" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version = "2.0.17" }

[plugins]
github-spotbugs = "com.github.spotbugs:6.4.4"
